### ISSUE TITLE
Out of date tor links

### ISSUE THREAD

**Issue by tgeek77** [OhShINT/ohshint.gitbook.io#3]
I did a quick grep of all of the .onion services in your list, and you still have some with the short v2 urls. Those are no longer usable as of last year. 

Examples: 

`[PwnDB Onion](https://pwndb2am4tzkvold.onion/)`
`[H-Indexer](http://jncyepk6zbnosf4p.onion/onions.html)`
`whois -h torwhois.com facebookcorewwwi.onion`

**Comment by OhShINT** [comment]
Thanks for the heads-up, I have gone ahead and removed those old v2 URLs.
